### ISSUE TITLE
Should Docker images be available under different account?

### ISSUE THREAD

**Issue by Psirus** [BAMresearch/Reproducible-Science#2]
Currently, all the Docker images are under my account `christophpohl`. While I don't have a problem with that, no one else can update these, so that doesn't seem like a good long term strategy. Does BAM have a Dockerhub account? How would the permissions be handled?

**Comment by joergfunger** [comment]
Maybe we could register with the simulation@bam.de adress and then everyone with access to this email can acess the account? Though this will probably involve the central IT or the admins of BAMResearch @hdino @Spanholz

**Comment by Spanholz** [comment]
Central IT. We only manage our GitHub account.
